#!/usr/bin/env python3
"""Minimal MCP stdio server exposing a single `generate_greeting_page` tool.

Run:  python server.py          (stdio transport)
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone


def _read_message() -> dict | None:
    """Read a JSON-RPC message from stdin (Content-Length framing)."""
    headers: dict[str, str] = {}
    while True:
        line = sys.stdin.readline()
        if not line:
            return None
        line = line.strip()
        if line == "":
            break
        if ":" in line:
            k, v = line.split(":", 1)
            headers[k.strip()] = v.strip()

    length = int(headers.get("Content-Length", "0"))
    if length == 0:
        return None
    body = sys.stdin.read(length)
    return json.loads(body)


def _send(msg: dict) -> None:
    """Write a JSON-RPC message to stdout with Content-Length framing."""
    body = json.dumps(msg)
    sys.stdout.write(f"Content-Length: {len(body)}\r\n\r\n{body}")
    sys.stdout.flush()


def _respond(req_id, result):
    _send({"jsonrpc": "2.0", "id": req_id, "result": result})


TOOL_DEF = {
    "name": "generate_greeting_page",
    "description": "Generate an HTML greeting page with a custom message and color theme",
    "inputSchema": {
        "type": "object",
        "properties": {
            "name": {"type": "string", "description": "Name to greet"},
            "color": {"type": "string", "description": "Theme color (hex)", "default": "#6366f1"},
        },
        "required": ["name"],
    },
}


def _handle_tool_call(name: str, args: dict) -> list[dict]:
    if name != "generate_greeting_page":
        return [{"type": "text", "text": f"Unknown tool: {name}"}]

    person = args.get("name", "World")
    color = args.get("color", "#6366f1")
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Hello {person}</title>
<style>
body {{ margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center;
       background:linear-gradient(135deg,{color}22,{color}44); font-family:system-ui }}
.card {{ background:#fff; border-radius:16px; padding:48px 64px; box-shadow:0 8px 32px {color}33; text-align:center }}
h1 {{ color:{color}; font-size:2.5rem; margin:0 0 8px }}
p {{ color:#64748b; font-size:1rem }}
</style></head>
<body><div class="card">
  <h1>Hello, {person}!</h1>
  <p>Generated by VibeOS MCP Tool at {ts}</p>
</div></body></html>"""
    return [{"type": "text", "text": html}]


def main():
    while True:
        msg = _read_message()
        if msg is None:
            break

        method = msg.get("method", "")
        req_id = msg.get("id")
        params = msg.get("params", {})

        if method == "initialize":
            _respond(req_id, {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {"listChanged": False}},
                "serverInfo": {"name": "hello-mcp", "version": "1.0.0"},
            })
        elif method == "notifications/initialized":
            pass
        elif method == "tools/list":
            _respond(req_id, {"tools": [TOOL_DEF]})
        elif method == "tools/call":
            tool_name = params.get("name", "")
            arguments = params.get("arguments", {})
            content = _handle_tool_call(tool_name, arguments)
            _respond(req_id, {"content": content, "isError": False})
        elif req_id is not None:
            _send({"jsonrpc": "2.0", "id": req_id, "error": {"code": -32601, "message": f"Unknown method: {method}"}})


if __name__ == "__main__":
    main()
