#!/usr/bin/env python3
"""Minimal MCP stdio server using the official SDK.

Exposes a single `generate_greeting_page` tool that returns HTML.

Run:  python server.py
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

app = Server("hello-mcp")


@app.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="generate_greeting_page",
            description="Generate an HTML greeting page with a custom message and color theme",
            inputSchema={
                "type": "object",
                "properties": {
                    "name": {"type": "string", "description": "Name to greet"},
                    "color": {"type": "string", "description": "Theme color (hex)", "default": "#6366f1"},
                },
                "required": ["name"],
            },
        )
    ]


@app.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    if name != "generate_greeting_page":
        return [TextContent(type="text", text=f"Unknown tool: {name}")]

    person = arguments.get("name", "World")
    color = arguments.get("color", "#6366f1")
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Hello {person}</title>
<style>
body {{ margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center;
       background:linear-gradient(135deg,{color}22,{color}44); font-family:system-ui }}
.card {{ background:#fff; border-radius:16px; padding:48px 64px; box-shadow:0 8px 32px {color}33; text-align:center }}
h1 {{ color:{color}; font-size:2.5rem; margin:0 0 8px }}
p {{ color:#64748b; font-size:1rem }}
.badge {{ margin-top:16px; display:inline-block; padding:6px 16px; background:{color}15; border-radius:999px;
          color:{color}; font-size:0.85rem; font-weight:500 }}
</style></head>
<body><div class="card">
  <h1>Hello, {person}!</h1>
  <p>Generated by VibeOS MCP Tool &middot; {ts}</p>
  <span class="badge">Unified Capability Registry E2E</span>
</div></body></html>"""
    return [TextContent(type="text", text=html)]


async def main():
    async with stdio_server() as (read_stream, write_stream):
        await app.run(read_stream, write_stream, app.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
